name: GitHub Metrics
on:
  schedule:
    - cron: "0 0 * * *"   # met Ã  jour tous les jours
  workflow_dispatch:      # permet de lancer manuellement
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # FICHIER DE SORTIE
          filename: github-metrics.svg

          # MODULES DE BASE
          base: header, activity, community, repositories, metadata

          # OPTIONS
          config_timezone: Africa/Dakar
