name: GitHub Metrics
on:
  schedule:
    - cron: "0 0 * * *"   # mise √† jour quotidienne √† minuit
  workflow_dispatch:      # permet de lancer manuellement

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # üîë essentiel pour push le SVG dans le repo
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}  # classic personal access token

          # Nom du fichier g√©n√©r√©
          filename: github-metrics.svg

          # Modules de base
          base: header, activity, community, repositories, metadata

          # Options suppl√©mentaires
          config_timezone: Africa/Dakar
